<div class="container">
    <h3>Liste des projets</h3>
    <p class="d-inline-flex gap-1">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Ajouter <i class="fa-solid fa-plus"></i>
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action="/ecf7/create/projet" method="post">
                <div class="mb-3">
                    <label for="Chef de projet" class="form-label">Chef de projet</label>
                    <input type="text" name="cdp" class="form-control" id="cdp" aria-describedby="cdp">
                </div>
                <div class="mb-3">
                    <label for="type" class="form-label">Type</label>
                    <input type="text" name="type" class="form-control" id="type">
                </div>
                <div class="mb-3">
                    <label for="prix" class="form-label">Statut</label>
                    <input type="text" name="statut" class="form-control" id="statut">
                </div>
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Chef de projet</th>
            <th scope="col">Type</th>
            <th scope="col">Prix</th>
            <th scope="col">Statut</th>
            <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->projets as $projet) { ?>
            <tr>
                <td><?php echo $projet['id']; ?></td>
                <td><?php echo $projet['cdp']; ?></td>
                <td><?php echo $projet['type']; ?></td>
                <td><?php echo $projet['prix']; ?></td>
                <td><?php echo $projet['statut']; ?></td>
                <td class="d-flex justify-content-around">
                    <button class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i> Editer</button>
                    <button class="btn btn-danger"><i class="fa-solid fa-trash"></i> Supprimer</button>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

</div>

