<div class="container">
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Chef de projet</th>
        <th scope="col">Type</th>
        <th scope="col">Prix</th>
        <th scope="col">Statut</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->view->projets as $projet) { ?>
    <tr>
        <td><?php echo $projet['id']; ?></td>
        <th><?php echo $projet['cdp']; ?></th>
        <th><?php echo $projet['type']; ?></th>
        <th><?php echo $projet['prix']; ?></th>
        <th><?php echo $projet['statut']; ?></th>
    </tr>
        <?php } ?>
    </tbody>
</table>

</div>

