<div class="container">
    <h3>Liste des équipes</h3>
    <p class="d-inline-flex gap-1">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Ajouter <i class="fa-solid fa-plus"></i>
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action="/ecf7/create/equipe" method="post">
                <div class="mb-3">
                    <label for="cdp" class="form-label">Chef de projet</label>
                    <select class="form-select" name="cdp" aria-label="Default select example">
                        <option selected disabled>--Sélectionner--</option>
                        <?php foreach ($this->view->cdp as $cdp) { ?>
                            <option value="<?php echo $cdp['id'] ?>"><?php echo $cdp['cdp'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="libelle" class="form-label">Libellé</label>
                    <input type="text" name="libelle" class="form-control" id="libelle" placeholder="--Nom d'équipe--">
                </div>
                <div class="mb-3">
                    <label for="membre">Ajouter des membres</label>
                    <?php foreach ($this->view->membre as $m) { ?>
                        <label class="btn btn-outline-primary" for="btnradio1"><?= $m['developpeur']; ?></label>
                    <input type="checkbox" value="<?php echo $m['id'] ?>" name="membre" autocomplete="off">
                    <?php } ?>
                </div>
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>
    </div>
    <table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Chef de projet</th>
        <th scope="col">Libelle</th>
        <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->view->equipe as $equipes) { ?>
    <tr>
        <td><?php echo $equipes['id']; ?></td>
        <td><?php echo $equipes['cdp']; ?></td>
        <td><?php echo $equipes['libelle']; ?></td>
        <td class="d-flex justify-content-around">
            <form action="/ecf7/equipe/show" method="get">
                <input type="hidden" name="id" value="<?php echo $equipes['id']; ?>">
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-circle-info"></i> Détails</button>
            </form>
            <form action="/ecf7/equipe/editEquipe" method="get">
                <input type="hidden" name="id" value="<?php echo $equipes['id']; ?>">
                <button type="submit" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i> Editer</button>
            </form>
            <form action="/ecf7/delete/equipe" method="get">
                <input type="hidden" name="id" value="<?php echo $equipes['id']; ?>">
                <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Supprimer</button>
            </form>
        </td>
    </tr>
        <?php } ?>
    </tbody>
</table>
</div>