<div class="container">
    <h3>Liste des équipes</h3>
    <p class="d-inline-flex gap-1">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Ajouter <i class="fa-solid fa-plus"></i>
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action=""></form>
        </div>
    </div>
    <table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Chef de projet</th>
        <th scope="col">Libelle</th>
        <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->view->equipe as $equipe) { ?>
    <tr>
        <td><?php echo $equipe['id']; ?></td>
        <td><?php echo $equipe['cdp']; ?></td>
        <td><?php echo $equipe['libelle']; ?></td>
        <td>
            <form action="/ecf7/delete/equipe" method="get">
                <input type="hidden" name="id" value="<?php echo $equipe['id']; ?>">
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#supprimer">
                    <i class="fa-solid fa-trash"></i> Supprimer
                </button>
                <button type="submit" class="btn btn-danger">Supprimer</button>
            </form>
        </td>
    </tr>
        <?php } ?>
    </tbody>
</table>

</div>