<div class="container">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="collaborateur">Collaborateurs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="developpeur">Développeurs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="chefdeprojet">Chef de projet</a>
        </li>
    </ul>

    <h3>Liste des chefs de projet</h3>
    <p class="d-inline-flex gap-1">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Ajouter <i class="fa-solid fa-plus"></i>
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action=""></form>
        </div>
        </div>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Collaborateur</th>
        <th scope="col">Boost de production</th>
        <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->view->cdp as $chef) { ?>
    <tr>
        <td><?php echo $chef['id']; ?></td>
        <td><?php echo $chef['nomCollabo']; ?></td>
        <td><?php echo $chef['boost']; ?></td>
        <td class="d-flex justify-content-around">
            <form action="">
                <input type="hidden" name="id" value="<?php echo $chef['id']; ?>">
                <button type="submit" class="btn btn-success">  <i class="fa-solid fa-pen-to-square"></i> Editer</button>
            </form>
            <form action="/ecf7/delete/chefdeprojet" method="get">
                <input type="hidden" name="id" value="<?php echo $chef['id']; ?>">
                <button type="submit" class="btn btn-danger">  <i class="fa-solid fa-trash"></i> Supprimer</button>
            </form>
        </td>
    </tr>
        <?php } ?>
    </tbody>
</table>

</div>